# Generated by Django 2.2.11 on 2020-03-24 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=128, unique=True, verbose_name='이메일')),
                ('phone_number', models.CharField(max_length=12, unique=True, verbose_name='전화번호')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일자')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=150, verbose_name='이름')),
                ('profile_image', models.URLField(blank=True, verbose_name='프로필이미지')),
                ('is_kids', models.BooleanField(default=False, verbose_name='키즈')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일자')),
                ('select_contents', models.ManyToManyField(related_name='profiles', to='contents.Contents', verbose_name='찜한 컨텐츠')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL, verbose_name='프로필')),
            ],
        ),
        migrations.CreateModel(
            name='Watching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playtime', models.CharField(max_length=10, verbose_name='재생시간')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watching', to='members.Profile', verbose_name='프로필')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watching', to='contents.Video', verbose_name='비디오')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='watching_videos',
            field=models.ManyToManyField(related_name='profiles', through='members.Watching', to='contents.Video', verbose_name='재생 중인 비디오'),
        ),
    ]
