# Generated by Django 2.2.11 on 2020-04-02 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileIconCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=128, verbose_name='아이콘 카테고리')),
            ],
        ),
        migrations.AlterField(
            model_name='profileicon',
            name='icon_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileIcons', to='members.ProfileIconCategory', verbose_name='아이콘 카테고리'),
        ),
    ]
