# Generated by Django 2.2.11 on 2020-03-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, unique=True, verbose_name='전화번호'),
        ),
    ]
