# Generated by Django 2.2.11 on 2020-04-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20200402_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='watching',
            name='video_length',
            field=models.PositiveIntegerField(default=0, verbose_name='비디오 길이'),
            preserve_default=False,
        ),
    ]
