# Generated by Django 2.2.11 on 2020-03-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_auto_20200320_1657'),
        ('members', '0002_auto_20200320_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='watching_videos',
            field=models.ManyToManyField(related_name='profiles', to='contents.Video', verbose_name='재생 중인 비디오'),
        ),
    ]
