# Generated by Django 2.2.11 on 2020-03-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_auto_20200320_1657'),
        ('members', '0003_profile_watching_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='select_contents',
            field=models.ManyToManyField(related_name='profiles', to='contents.Content', verbose_name='찜한 컨텐츠'),
        ),
    ]
