# Generated by Django 2.2.12 on 2020-04-22 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_auto_20200414_1947'),
        ('members', '0003_watching_video_length'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watching',
            unique_together={('video', 'profile')},
        ),
    ]
