# Generated by Django 2.2.11 on 2020-03-25 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_url', models.URLField()),
                ('icon_type', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_icon',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='members.ProfileIcon', verbose_name='프로필 이미지'),
        ),
    ]
