# Generated by Django 2.2.11 on 2020-03-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20200325_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileicon',
            name='icon_url',
            field=models.ImageField(upload_to='profile/icon/'),
        ),
        migrations.AlterField(
            model_name='watching',
            name='playtime',
            field=models.PositiveIntegerField(verbose_name='재생시간'),
        ),
    ]
