# Generated by Django 2.2.11 on 2020-03-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_profile_select_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='프로필이미지'),
        ),
    ]
