# Generated by Django 2.2.11 on 2020-03-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20200326_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='select_contents',
            field=models.ManyToManyField(null=True, related_name='profiles', to='contents.Contents', verbose_name='찜한 컨텐츠'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='watching_videos',
            field=models.ManyToManyField(null=True, related_name='profiles', through='members.Watching', to='contents.Video', verbose_name='재생 중인 비디오'),
        ),
    ]
