# Generated by Django 2.2.11 on 2020-03-26 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20200326_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_icon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='members.ProfileIcon', verbose_name='프로필 이미지'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='select_contents',
            field=models.ManyToManyField(related_name='profiles', to='contents.Contents', verbose_name='찜한 컨텐츠'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='watching_videos',
            field=models.ManyToManyField(related_name='profiles', through='members.Watching', to='contents.Video', verbose_name='재생 중인 비디오'),
        ),
    ]
