# Generated by Django 2.2.11 on 2020-03-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20200326_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileicon',
            name='icon_name',
            field=models.CharField(default=' ', max_length=128, verbose_name='아이콘 이름'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profileicon',
            name='icon',
            field=models.ImageField(upload_to='profile/icon/', verbose_name='아이콘'),
        ),
        migrations.AlterField(
            model_name='profileicon',
            name='icon_type',
            field=models.CharField(max_length=64, verbose_name='아이콘 타입'),
        ),
    ]
