# Generated by Django 2.2.11 on 2020-03-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_auto_20200326_1603'),
        ('members', '0009_auto_20200326_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='like_contents',
            field=models.ManyToManyField(related_name='like_profiles', to='contents.Contents', verbose_name='평가한 컨텐츠'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='select_contents',
            field=models.ManyToManyField(related_name='select_profile', to='contents.Contents', verbose_name='찜한 컨텐츠'),
        ),
    ]
