# Generated by Django 2.2.11 on 2020-03-30 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20200327_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileicon',
            old_name='icon_type',
            new_name='icon_category',
        ),
    ]
