# Generated by Django 2.2.11 on 2020-03-24 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents_title', models.CharField(max_length=150)),
                ('contents_summary', models.TextField(blank=True)),
                ('contents_image', models.ImageField(blank=True, upload_to='')),
                ('contents_rating', models.IntegerField(choices=[(0, '전체이용가'), (12, '12세이용가'), (15, '15세이용가'), (18, '청소년이용불가')], default=0)),
                ('is_movie', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_season', models.CharField(blank=True, max_length=150)),
                ('video_title', models.CharField(max_length=150)),
                ('video_summary', models.CharField(blank=True, max_length=150)),
                ('video_url', models.URLField()),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='contents.Contents', verbose_name='컨텐츠')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150)),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='contents.Contents', verbose_name='카테고리')),
            ],
        ),
    ]
