# Generated by Django 2.2.11 on 2020-04-01 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents_title', models.CharField(max_length=150)),
                ('contents_title_english', models.CharField(blank=True, max_length=150)),
                ('contents_summary', models.TextField(blank=True)),
                ('contents_image', models.ImageField(blank=True, upload_to='contents/image/')),
                ('contents_logo', models.ImageField(blank=True, upload_to='contents/logo/')),
                ('contents_rating', models.CharField(max_length=64)),
                ('contents_length', models.CharField(max_length=64)),
                ('contents_pub_year', models.CharField(max_length=8)),
                ('is_movie', models.BooleanField(default=True)),
                ('actors', models.ManyToManyField(related_name='contents', to='contents.Actor', verbose_name='출연 배우')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_season', models.CharField(blank=True, max_length=150)),
                ('video_title', models.CharField(max_length=150)),
                ('video_summary', models.CharField(blank=True, max_length=150)),
                ('video_url', models.URLField()),
                ('contents', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='contents.Contents', verbose_name='컨텐츠')),
            ],
        ),
        migrations.AddField(
            model_name='contents',
            name='directors',
            field=models.ManyToManyField(related_name='contents', to='contents.Director', verbose_name='감독'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150)),
                ('contents', models.ManyToManyField(related_name='categories', to='contents.Contents', verbose_name='카테고리')),
            ],
        ),
    ]
