# Generated by Django 2.2.11 on 2020-04-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='preview_video',
            field=models.URLField(null=True),
        ),
    ]
