# Generated by Django 2.2.11 on 2020-03-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='content',
            name='thumbnail',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sub_categories', models.ManyToManyField(to='contents.SubCategory')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='categories',
            field=models.ManyToManyField(to='contents.Category'),
        ),
    ]
