# Generated by Django 2.2.11 on 2020-03-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='content',
            new_name='contents',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='content',
            new_name='contents',
        ),
        migrations.AddField(
            model_name='contents',
            name='actors',
            field=models.ManyToManyField(related_name='contents', to='contents.Actor', verbose_name='출연 배우'),
        ),
        migrations.AddField(
            model_name='contents',
            name='directors',
            field=models.ManyToManyField(related_name='contents', to='contents.Director', verbose_name='감독'),
        ),
    ]
