# Generated by Django 2.2.11 on 2020-04-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_contents_preview_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('1', '드라마'), ('2', '판타지'), ('3', '서부'), ('4', '공포'), ('5', '로맨스'), ('6', '모험'), ('7', '스릴러'), ('8', '느와르'), ('9', '컬트'), ('10', '다큐멘터리'), ('11', '코미디'), ('12', '가족'), ('13', '미스터리'), ('14', '전쟁'), ('15', '애니메이션'), ('16', '범죄'), ('17', '뮤지컬'), ('18', 'SF'), ('19', '액션'), ('20', '무협'), ('21', '에로'), ('22', '서스펜스'), ('23', '서사'), ('24', '블랙코미디'), ('25', '실험'), ('26', '영화카툰'), ('27', '영화음악'), ('28', '영화패러디포스터')], max_length=150),
        ),
        migrations.AlterField(
            model_name='contents',
            name='contents_logo',
            field=models.ImageField(null=True, upload_to='contents/logo/'),
        ),
    ]
