# Generated by Django 2.2.11 on 2020-03-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_auto_20200324_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='contents_length',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='contents',
            name='contents_logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contents',
            name='contents_pub_year',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
