# Generated by Django 2.2.11 on 2020-03-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_auto_20200325_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='contents_image',
            field=models.ImageField(blank=True, upload_to='contents/image'),
        ),
        migrations.AlterField(
            model_name='contents',
            name='contents_logo',
            field=models.ImageField(blank=True, upload_to='contents/logo'),
        ),
        migrations.AlterField(
            model_name='contents',
            name='contents_rating',
            field=models.IntegerField(choices=[(0, '전체 관람가'), (12, '12세 관람가'), (15, '15세 관람가'), (18, '청소년 관람불가')], default=0),
        ),
    ]
