# Generated by Django 2.2.11 on 2020-03-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_auto_20200326_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='contents',
        ),
        migrations.AddField(
            model_name='category',
            name='contents',
            field=models.ManyToManyField(related_name='categories', to='contents.Contents', verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='contents',
            name='contents_image',
            field=models.ImageField(blank=True, upload_to='contents/image/'),
        ),
        migrations.AlterField(
            model_name='contents',
            name='contents_length',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='contents',
            name='contents_logo',
            field=models.ImageField(blank=True, upload_to='contents/logo/'),
        ),
        migrations.AlterField(
            model_name='contents',
            name='contents_pub_year',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='contents',
            name='contents_rating',
            field=models.CharField(max_length=64),
        ),
    ]
